//Operators pulled from ServiceNow glide query
export const opdef = {
  af: ['>', 'after'],
  ataf: ['>=', 'at or after'],
  any: ['ANYTHING', 'is anything'],
  are: ['=', 'are'],
  asc: ['ascending', 'a to z'],
  avg: ['avg', 'average'],
  bf: ['<', 'before'],
  atbf: ['<=', 'at or before'],
  btw: ['BETWEEN', 'between'],
  dsc: ['descending', 'z to a'],
  dsw: ['DISTANCE_SPHERE_WITHIN', 'distance within'],
  dtpt: ['DATEPART', 'trend'],
  em: ['ISEMPTY', 'is empty'],
  es: ['EMPTYSTRING', 'is empty string'],
  enwt: ['ENDSWITH', 'ends with'],
  eq: ['=', 'is'],
  eqd: ['DYNAMIC', 'is (dynamic)'],
  fvc: ['VALCHANGES', 'changes'],
  fvf: ['CHANGESFROM', 'changes from'],
  fvt: ['CHANGESTO', 'changes to'],
  gt: ['>', 'greater than'],
  gteq: ['>=', 'greater than or is'],
  inna: ['IN', 'is one of'],
  inst: ['INSTANCEOF', 'is a'],
  lk: ['LIKE', 'contains'],
  lt: ['<', 'less than'],
  lteq: ['<=', 'less than or is'],
  max: ['max', 'maximum'],
  min: ['min', 'minimum'],
  mpat: ['MATCH_PAT', 'matches pattern'],
  mreg: ['MATCH_RGX', 'matches regex'],
  ntem: ['ISNOTEMPTY', 'is not empty'],
  nteq: ['!=', 'is not'],
  ntin: ['NOT IN', 'is not one of'],
  ntlk: ['NOT LIKE', 'does not contain'],
  nton: ['NOTON', 'not on'],
  on: ['ON', 'on'],
  oper: ['-- oper --', '-- oper --'],
  rltv: ['RELATIVE', 'relative'],
  saas: ['SAMEAS', 'is same'],
  nsas: ['NSAMEAS', 'is different'],
  snc: ['SINCE', 'since baseline'],
  stwt: ['STARTSWITH', 'starts with'],
  sum: ['sum', 'Total'],
  date_more: ['MORETHAN', 'is more than'],
  date_less: ['LESSTHAN', 'is less than'],
  gtfd: ['GT_FIELD', 'greater than field'],
  ltfd: ['LT_FIELD', 'less than field'],
  gteqfd: ['GT_OR_EQUALS_FIELD', 'greater than or is field'],
  lteqfd: ['LT_OR_EQUALS_FIELD', 'less than or is field'],
  inh: ['IN_HIERARCHY', 'is in hierarchy'],
  inhd: ['IN_HIERARCHY_DYNAMIC', 'is in hierarchy (dynamic)'],
}

export const sysopers = {
  auto_increment: '=integer',
  aggspec: 'sum,avg,min,max,any,fvc,fvf,fvt',
  boolean: 'eq,nteq,em,ntem,any,fvc,fvf,fvt,saas,nsas',
  calendar: 'on,nton,bf,atbf,af,ataf,btw,dtpt,rltv,snc,em,ntem,any,fvc,saas,nsas,date_more,date_less',
  choice: 'eq,nteq,inna,ntin,lk,stwt,enwt,ntlk,any,fvc,fvf,fvt,saas,nsas',
  referencechoice: 'eq,nteq,inna,ntin,lk,stwt,enwt,ntlk,any',
  composite_field: 'stwt,lk,ntlk,any',
  composite_name: '=string',
  conditions: '=string',
  condition_string: '=string',
  css: '=html',
  decimal: '=integer',
  currency: 'eq,nteq,em,ntem,lt,gt,lteq,gteq,btw',
  currency2: 'eq,nteq,em,ntem,lt,gt,lteq,gteq,btw',
  default: 'eq,nteq,any,fvc,fvf,fvt',
  email: '=string',
  email_script: '=string',
  field_name: '=string',
  geo_point: 'eq,nteq,dsw',
  glide_duration: 'eq,nteq,em,ntem,lt,gt,lteq,gteq,btw,any,fvc',
  glide_encrypted: 'eq,nteq,em,ntem',
  glide_list: 'lk,ntlk,em,ntem,fvc,fvf,fvt,eqd',
  GUID: '=string',
  html: 'lk,ntlk,em,ntem,any,fvc,fvf,fvt',
  html_script: '=string',
  html_template: '=script',
  ip_addr: '=string',
  integer: 'eq,nteq,em,ntem,lt,gt,lteq,gteq,btw,any,fvc,fvf,fvt,saas,nsas,gtfd,ltfd,gteqfd,lteqfd',
  integer_choice: 'eq,nteq,inna,ntin,em,ntem,lt,gt,lteq,gteq,btw,any,fvc,fvf,fvt,saas,nsas',
  journal: 'fvc',
  journal_input: '=journal',
  keyword: 'are',
  long: '=integer',
  longint: '=integer',
  multi_two_lines: '=string',
  percent_complete: '=integer',
  ph_number: '=string',
  phone_number_e164: '=string',
  placeholder: 'oper',
  price: 'eq,nteq,em,ntem,lt,gt,lteq,gteq,btw',
  reference: 'eq,nteq,em,ntem,stwt,enwt,lk,ntlk,any,saas,nsas,es,eqd,fvc,fvf,fvt,inh,inhd',
  referencevariable: 'eq,nteq,em,ntem',
  replication_payload: '=string',
  script: 'lk,ntlk,ntem,any,fvc,fvf,fvt',
  script_plain: '=script',
  script_server: '=script',
  sortspec: 'asc,dsc,fvc,fvf,fvt',
  string: 'stwt,enwt,lk,ntlk,eq,nteq,em,ntem,mpat,mreg,any,inna,es,fvc,fvf,fvt,lteq,gteq,btw,saas,nsas',
  string_choice: '=choice',
  string_clob: 'lk,ntlk,stwt,enwt,em,ntem,any,fvc,fvf,fvt',
  string_full_utf8: '=string',
  string_numeric: 'eq,nteq,lk,ntlk,stwt,enwt,btw,any,fvc,fvf,fvt,saas,nsas',
  sys_class_name: 'eq,nteq,inst,any,fvc,fvf,fvt',
  sysevent_name: '=string',
  table_name: '=string',
  timer: '=integer',
  translated_field: '=string',
  translated_html: '=html',
  translated_text: '=string',
  translated_basic: 'eq,nteq,em,ntem',
  url: '=string',
  workflow: '=choice',
  xml: '=html',
  domain_path: '=string',
  tree_code: '=string',
  tree_path: '=string',
  source_id: '=string',
  source_name: '=string',
  source_table: '=string',
  sc_attachment: 'em,ntem',
  related_tags: 'eq,nteq,em,ntem,stwt,lk',
}

export function getOperatorsForType(type: string): string[] {
  const ops = sysopers[type as keyof typeof sysopers]
  if (!ops) return []

  if (ops.startsWith('=')) {
    const chainedType = ops.slice(1)
    return getOperatorsForType(chainedType)
  }

  return ops.split(',')
}

export function getChangeOperators(type: string) {
  const baseOps = getOperatorsForType(type)
  if (!baseOps.length) baseOps.push('fvc')

  return baseOps.filter(op => ['fvc', 'fvf', 'fvt'].includes(op))
}