const choicePredicates = ['IN', 'NOT IN', 'LIKE', 'NOT LIKE', 'STARTSWITH', 'ENDSWITH'] as const

const booleanPredicates = ['=', '!=', 'ISEMPTY', 'ISNOTEMPTY', 'ANYTHING', 'SAMEAS', 'NSAMEAS'] as const

const referencePredicates = [
  '=',
  '!=',
  'ISEMPTY',
  'ISNOTEMPTY',
  'STARTSWITH',
  'ENDSWITH',
  'LIKE',
  'NOT LIKE',
  'ANYTHING',
  'SAMEAS',
  'NSAMEAS',
  'EMPTYSTRING',
  'DYNAMIC',
] as const

const stringPredicates = [
  'STARTSWITH',
  'ENDSWITH',
  'LIKE',
  'NOT LIKE',
  '=',
  '!=',
  'ISEMPTY',
  'ISNOTEMPTY',
  'MATCH_PAT',
  'MATCH_RGX',
  'ANYTHING',
  'IN',
  'EMPTYSTRING',
  '<=',
  '>=',
  'BETWEEN',
  'SAMEAS',
  'NSAMEAS',
] as const

const numericPredicates = [
  '=',
  '!=',
  'ISEMPTY',
  'ISNOTEMPTY',
  '<',
  '>',
  '<=',
  '>=',
  'BETWEEN',
  'ANYTHING',
  'SAMEAS',
  'NSAMEAS',
  'GT_FIELD',
  'LT_FIELD',
  'GT_OR_EQUALS_FIELD',
  'LT_OR_EQUALS_FIELD',
] as const

const datePredicates = [
  'ON',
  'NOTON',
  '<',
  '<=',
  '>',
  '>=',
  'BETWEEN',
  'DATEPART',
  'RELATIVE',
  'ISEMPTY',
  'ISNOTEMPTY',
  'ANYTHING',
  'SAMEAS',
  'NSAMEAS',
  'MORETHAN',
  'LESSTHAN',
] as const

export const predicateMap: Record<string, readonly string[]> = {
  choice: choicePredicates,
  string: stringPredicates,
  date: datePredicates,
  numeric: numericPredicates,
  boolean: booleanPredicates,
  reference: referencePredicates,
}

export function getAllPredicates(): string[] {
  return Array.from(
    new Set([
      ...choicePredicates,
      ...stringPredicates,
      ...datePredicates,
      ...numericPredicates,
      ...booleanPredicates,
      ...referencePredicates,
    ])
  )
}

export const fieldTypeMap: Record<string, string> = {
  password2: 'string',
  glide_encrypted: 'string',
  currency2: 'GUID',
  nds_icon: 'string',
  boolean: 'boolean',
  calendar_date_time: 'datetime',
  data_structure: 'string',
  due_date: 'datetime',
  icon: 'string',
  password: 'string',
  translated_html: 'string',
  dynamic_attribute_store: 'string',
  geo_point: 'string',
  audio: 'string',
  conditions: 'string',
  script: 'string',
  html: 'string',
  ip_addr: 'string',
  field_name: 'string',
  journal_input: 'string',
  journal_list: 'string',
  choice: 'string',
  reference: 'GUID',
  longint: 'numeric',
  color: 'string',
  string_full_utf8: 'string',
  url: 'string',
  string: 'string',
  simple_name_values: 'string',
  percent_complete: 'numeric',
  float: 'numeric',
  glide_utc_time: 'datetime',
  glide_date: 'date',
  language: 'string',
  glide_date_time: 'datetime',
  glide_time: 'datetime',
  video: 'string',
  wiki_text: 'string',
  document_id: 'GUID',
  glide_duration: 'datetime',
  integer: 'numeric',
  phone_number_e164: 'string',
  script_plain: 'string',
  domain_id: 'GUID',
  workflow: 'string',
  table_name: 'string',
  glide_list: 'string',
  user_image: 'string',
  file_attachment: 'string',
  translated_text: 'string',
  journal: 'string',
  decimal: 'numeric',
  currency: 'numeric',
  price: 'numeric',
  condition_string: 'string',
}
