import type { LucideIcon } from 'lucide-react'
import {
  Archive,
  ArrowUpAZ,
  Book,
  BookMarked,
  BookOpen,
  Calendar,
  CircleCheck,
  CircleHelp,
  CreditCard,
  Database,
  Eye,
  FileCode,
  FileText,
  Filter,
  Folder,
  GitBranch,
  House,
  Image,
  Info,
  LayoutDashboard,
  Lightbulb,
  List,
  Lock,
  Mail,
  MessageCircle,
  Paperclip,
  Pencil,
  Plus,
  Power,
  Rss,
  Search,
  Settings,
  ShoppingCart,
  Smartphone,
  Star,
  StarOff,
  Tag,
  Terminal,
  TicketPlus,
  Trash2,
  TreePine,
  TriangleAlert,
  User,
  Users,
  X,
} from 'lucide-react'
import type { SnDecorationIcon } from '../types/form-schema'

export const SN_DECORATION_ICON_MAP: Record<SnDecorationIcon, LucideIcon> = {
  'icon-user': User,
  'icon-user-group': Users,
  'icon-lightbulb': Lightbulb,
  'icon-home': House,
  'icon-mobile': Smartphone,
  'icon-comment': MessageCircle,
  'icon-mail': Mail,
  'icon-locked': Lock,
  'icon-database': Database,
  'icon-book': Book,
  'icon-drawer': Archive,
  'icon-folder': Folder,
  'icon-catalog': BookMarked,
  'icon-tab': FileText,
  'icon-cards': CreditCard,
  'icon-tree-right': GitBranch,
  'icon-tree': TreePine,
  'icon-book-open': BookOpen,
  'icon-paperclip': Paperclip,
  'icon-edit': Pencil,
  'icon-trash': Trash2,
  'icon-image': Image,
  'icon-search': Search,
  'icon-power': Power,
  'icon-cog': Settings,
  'icon-star': Star,
  'icon-star-empty': StarOff,
  'icon-new-ticket': TicketPlus,
  'icon-dashboard': LayoutDashboard,
  'icon-cart-full': ShoppingCart,
  'icon-view': Eye,
  'icon-label': Tag,
  'icon-filter': Filter,
  'icon-calendar': Calendar,
  'icon-script': FileCode,
  'icon-add': Plus,
  'icon-delete': X,
  'icon-help': CircleHelp,
  'icon-info': Info,
  'icon-check-circle': CircleCheck,
  'icon-alert': TriangleAlert,
  'icon-sort-ascending': ArrowUpAZ,
  'icon-console': Terminal,
  'icon-list': List,
  'icon-form': FileText,
  'icon-livefeed': Rss,
}

export function isSupportedSnDecorationIcon(icon: string): icon is SnDecorationIcon {
  return Object.prototype.hasOwnProperty.call(SN_DECORATION_ICON_MAP, icon)
}
